using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
// <copyright file="ProgramTest.GetNextPermutation.g.cs">Copyright ©  2015</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;
using System.Linq;

namespace Problem24
{
    public partial class ProgramTest
    {
        [TestMethod]
        [PexGeneratedBy(typeof(ProgramTest))]
        public void GetNextPermutation1234()
        {
            int[] ints = new int[] { 1, 2, 3, 4 };
            int[] expected = new int[] { 1, 2, 4, 3 };
            ints = GetNextPermutation(ints);
            Assert.IsTrue(Enumerable.SequenceEqual(ints, expected));
        }

        [TestMethod]
        [PexGeneratedBy(typeof(ProgramTest))]
        public void GetNextPermutation1324()
        {
            int[] ints = new int[] { 1, 3, 2, 4 };
            int[] expected = new int[] { 1, 3, 4, 2 };
            ints = GetNextPermutation(ints);
            Assert.IsTrue(Enumerable.SequenceEqual(ints, expected));
        }

        [TestMethod]
        [PexGeneratedBy(typeof(ProgramTest))]
        public void GetNextPermutation3124()
        {
            int[] ints = new int[] { 3, 1, 2, 4 };
            int[] expected = new int[] { 3, 1, 4, 2 };
            ints = GetNextPermutation(ints);
            Assert.IsTrue(Enumerable.SequenceEqual(ints, expected));
        }

        [TestMethod]
        [PexGeneratedBy(typeof(ProgramTest))]
        public void GetNextPermutation1342()
        {
            int[] ints = new int[] { 1, 3, 4, 2 };
            int[] expected = new int[] { 1, 4, 2, 3 };
            ints = GetNextPermutation(ints);
            Assert.IsTrue(Enumerable.SequenceEqual(ints, expected));
        }


        [TestMethod]
        [PexGeneratedBy(typeof(ProgramTest))]
        public void GetNextPermutation2143()
        {
            int[] ints = new int[] { 2, 1, 4, 3 };
            int[] expected = new int[] { 2, 3, 1, 4 };
            ints = GetNextPermutation(ints);
            Assert.IsTrue(Enumerable.SequenceEqual(ints, expected));
        }


        [TestMethod]
        [PexGeneratedBy(typeof(ProgramTest))]
        public void GetNextPermutation12345()
        {
            int[] ints = new int[] { 1, 2, 3, 4, 5 };
            int[] expected = new int[] { 1, 2, 3, 5, 4 };
            ints = GetNextPermutation(ints);
            Assert.IsTrue(Enumerable.SequenceEqual(ints, expected));
        }
    }
}
