using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
// <copyright file="ProgramTest.GetRecurringCycle.g.cs">Copyright ©  2015</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace Problem26
{
    public partial class ProgramTest
    {
        [TestMethod]
        [PexGeneratedBy(typeof(ProgramTest))]
        public void GetRecurringCycle1by7()
        {
            string s;
            s = this.GetRecurringCycle(1, 7);
            Assert.AreEqual<string>("142857", s);
        }

        [TestMethod]
        [PexGeneratedBy(typeof(ProgramTest))]
        public void GetRecurringCycle1by3()
        {
            string s;
            s = this.GetRecurringCycle(1, 3);
            Assert.AreEqual<string>("3", s);
        }

        [TestMethod]
        [PexGeneratedBy(typeof(ProgramTest))]
        public void GetRecurringCycle1by6()
        {
            string s;
            s = this.GetRecurringCycle(1, 6);
            Assert.AreEqual<string>("6", s);
        }

        [TestMethod]
        [PexGeneratedBy(typeof(ProgramTest))]
        public void GetRecurringCycle1by9()
        {
            string s;
            s = this.GetRecurringCycle(1, 9);
            Assert.AreEqual<string>("1", s);
        }

        [TestMethod]
        [PexGeneratedBy(typeof(ProgramTest))]
        public void GetRecurringCycle1by11()
        {
            string s;
            s = this.GetRecurringCycle(1, 11);
            Assert.AreEqual<string>("09", s);
        }

        [TestMethod]
        [PexGeneratedBy(typeof(ProgramTest))]
        public void GetRecurringCycle1by5()
        {
            string s;
            s = this.GetRecurringCycle(1, 5);
            Assert.AreEqual<string>("0", s);
        }

        [TestMethod]
        [PexGeneratedBy(typeof(ProgramTest))]
        public void GetRecurringCycle1by4()
        {
            string s;
            s = this.GetRecurringCycle(1, 4);
            Assert.AreEqual<string>("0", s);
        }

        [TestMethod]
        [PexGeneratedBy(typeof(ProgramTest))]
        public void GetRecurringCycle1by10()
        {
            string s;
            s = this.GetRecurringCycle(1, 10);
            Assert.AreEqual<string>("0", s);
        }
    }
}
